### ISSUE TITLE
required only if value exists/not empty?

### ISSUE THREAD

**Issue by tdias25** [rakit/validation#34]
i'm new at using this library, and i am looking for an option that only validates if the field is not empty, if empty "remove" from valid data, its because i have an update user page, and the blank fields are not to update

**Comment by Vandervir** [comment]
https://github.com/rakit/validation#present

**Comment by tdias25** [comment]
i know its confusing, but it should ignore the value if its empty

**Comment by emsifa** [comment]
Rule `present` doing something like `isset` function, if it's not set, it would return `false` (invalid). 

In your code above field `id` is not present because it's not set (you comment it), so `isset($data['id'])` would return `false`.

If you want to make `id` optional even the key is not exists, you can use `numeric` rule only.

**Comment by tdias25** [comment]
i did it with email field, only used the email rule without the required, and it still passes the validation, the field was blank

**Comment by tdias25** [comment]
its like it is bypassing the validation, or am i mising something silly?

**Comment by emsifa** [comment]
I think I'm miss your point. Are you having problem with `getValidData()`?
