### ISSUE TITLE
array member validate failed，buy it's not exist!

### ISSUE THREAD

**Issue by sammeishi** [rakit/validation#42]
$data = [
"a"=>true,
"b"=>[
   "b1"=>true
]
];
$validation = $validator->make($data, [
    'a'                  => 'required',
    'b.test'                  => 'accepted',
]);

got error:
The b.test must be accepted!

should be passed?

**Comment by emsifa** [comment]
`accepted` is implicit rule. Implicit rule would still validated even if the key is empty or doesn't exists.

It's because `accepted` rule commonly used for input checkbox that doesn't sent it's key/name to `$_POST` data when it's not checked.

In your code, `b.test` is not valid because your array `b` doesn't have `test` key.

**Comment by emsifa** [comment]
If you want non-implicit rule, you can use `in` instead. For example:

```php
$validation = $validator->make($data, [
    'a' => 'required',
    'b.test' => [$validator('in', [true, false])->strict()]
]);
```

I will close this. If you have another question, you can open it again.
